
version: '3.9' # or '2.4'      # add
services:                      # addjupyterlab:
  
    build: ./jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./data:/var/lib/jupyter-lab/data
    entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/opt/app/data --allow-root'
